site_name: Machine Learning Tutorial

repo_url: https://github.com/European-XFEL/machine_learning_tutorial.git

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # scheme: preference
  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github

  features:
    - content.code.select
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

nav:
  - Home: index.md
  - Linear Regression:
    - linreg/index.md
    - Closed-form solution: linreg/closed_form.md
  - Neutral Networks:
    - nnets/index.md 
    - The neural network class: nnets/neural_networks.md
    - Testing with a simple dataset: nnets/neural_network_testing.md

plugins:
  - search
  - pseudocode
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css  
  - stylesheets/pseudo-code.css

